/* $OpenBSD: version.h,v 1.83 2018/10/10 16:43:49 deraadt Exp $ */

#define SSH_VERSION	"OQS-OpenSSH_7.9-2020-08_"

#define SSH_PORTABLE	"p1"
#define SSH_RELEASE_MINIMUM	SSH_VERSION SSH_PORTABLE
#ifdef SSH_EXTRAVERSION
#define SSH_RELEASE	SSH_RELEASE_MINIMUM " " SSH_EXTRAVERSION
#else
#define SSH_RELEASE	SSH_RELEASE_MINIMUM
#endif
